server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  web:
    resources:
      add-mappings: false
  datasource:
    url: ""
    username: 
    password: 
    driver-class-name: 
    hikari:
      schema: 
  jpa:
    properties:
      hibernate:
        default_schema: 
    hibernate:
      ddl-auto:
    show-sql:
    generate-ddl:

logging:
  level:
    com.zaxxer.hikari:
    org.hibernate.engine.jdbc.connections.internal:
    org.hibernate.orm.connections.pooling:

jwt:
  issuer:
  secret-key:
  private-key:
  public-key:
  access-token:
    valid-duration: # in seconds
  refresh-token:
    valid-duration: # in seconds
